In [153]:
import pandas as pd
import numpy as np

In [154]:
bint_df = pd.read_csv("BINT.csv")

In [155]:
bint_df

,STUID,DOB,GENDER,ETHNICITYID,ETHNICITY,CITYID,CITY,DISTRICTID,DISTRICT,FEEDERID,...,SEMESTERPOINTS,SEMESTERGPA,COURSECODE,COURSETITLE,COURSEGRADE,COURSECREDITS,COURSEPOINTS,COURSEGPA,COMMENTS,CGPA
0,1,3/20/1983,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,9.0,2.5,CMPS314,ALGORITHMS,B,3.0,9.0,3.0,NaN,3.26
1,1,3/20/1983,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,7.5,2.5,CMPS316,PROGRAMMING LANGUAGES,C+,3.0,7.5,2.5,NaN,3.26
2,1,3/20/1983,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,9.0,3.1,CMPS412,ADVANCED COMPUTER ARCHITECTURE,B,3.0,9.0,3.0,NaN,3.26
3,1,3/20/1983,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,10.5,3.5,MATH480,LINEAR PROGRAMMING.,B+,3.0,10.5,3.5,NaN,3.26
4,1,3/20/1983,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,7.5,2.5,CMPS312,COMPUTER ORG. & ASSEMBLY LANG. PROG.,C+,3.0,7.5,2.5,NaN,3.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8439,8423,6/13/1978,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,0.0,1.5,CMPS3151,TELECOMMUNICATION,F,3.0,0.0,0.0,NaN,2.01
8440,8423,6/13/1978,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,7.5,3.0,MATH1302,CALCULUS I,C+,3.0,7.5,2.5,NaN,2.01
8441,8423,6/13/1978,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,10.5,3.0,MGMT2055,BUSINESS ETHICS,B+,3.0,10.5,3.5,NaN,2.01
8442,8423,6/13/1978,F,8.0,Creole,"53,222",BELIZE CITY,75.0,BELIZE,164.0,...,3.0,1.9,MATH2201,CALCULUS II,D,3.0,3.0,1.0,NaN,2.01
8443,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
bint_df_drop = bint_df.drop(["ETHNICITYID", "CITYID", "DISTRICTID", "DEGREEID", "DEGREE", "FEEDERID", "COMMENTS", "CODE", "PROGRAM", "BREAK"], axis=1)

In [157]:
bint_df_clean =bint_df_drop.drop([8443],axis=0)

In [158]:
bint_df_clean.nunique()

STUID                       436
DOB                         426
GENDER                        2
ETHNICITY                    10
CITY                         48
DISTRICT                      8
FEEDER                       31
PROGRAMSTART                 86
PROGRAMSTATUS                 6
GRADDATE                     35
PROGRAMEND                   53
ENROLLEDSEMESTER             65
SEMESTERCREDITSATTEMPTED      6
SEMESTERCREDITSEARNED         6
SEMESTERPOINTS               30
SEMESTERGPA                 167
COURSECODE                  241
COURSETITLE                 189
COURSEGRADE                  17
COURSECREDITS                 6
COURSEPOINTS                 30
COURSEGPA                    10
CGPA                        173
dtype: int64

In [159]:
bint_df_clean_unique = bint_df_clean.drop_duplicates(subset="STUID")

In [160]:
bint_df_clean_unique

,STUID,DOB,GENDER,ETHNICITY,CITY,DISTRICT,FEEDER,PROGRAMSTART,PROGRAMSTATUS,GRADDATE,...,SEMESTERCREDITSEARNED,SEMESTERPOINTS,SEMESTERGPA,COURSECODE,COURSETITLE,COURSEGRADE,COURSECREDITS,COURSEPOINTS,COURSEGPA,CGPA
0,1,3/20/1983,F,Creole,BELIZE CITY,BELIZE,UNIVERSITY OF BELIZE,8/16/2004,Graduated,6/11/2006,...,3.0,9.0,2.50,CMPS314,ALGORITHMS,B,3.0,9.0,3.0,3.26
18,19,12/27/1980,F,Mestizo,ORANGE WALK,ORANGE WALK,UNIVERSITY OF BELIZE,8/19/2002,Graduated,6/11/2006,...,3.0,9.0,3.29,CMPS248,SOFTWARE IN SOCIETY,B,3.0,9.0,3.0,3.32
55,56,10/30/1981,M,Mestizo,BELMOPAN CITY,CAYO,UNIVERSITY OF BELIZE,8/18/2008,Terminated,NaN,...,0.0,0.0,0.38,MAT103,TRIGONOMETRY 1,WF,3.0,0.0,0.0,1.33
104,105,5/31/1976,M,Unknown,CAYO,BELIZE,*UNKNOWN,8/14/2002,Dropped,NaN,...,4.0,14.0,3.50,CMPS146,PROGRAMMING FOUNDATIONS,B+,4.0,14.0,3.5,3.62
108,109,8/4/1981,M,Unknown,CAYO,BELIZE,UNIVERSITY COLLEGE OF BELIZE,3/17/2005,Dropped,NaN,...,3.0,0.0,0.00,CMPS314,ALGORITHMS,F,3.0,0.0,0.0,1.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8321,8322,11/26/1973,M,Other,BELMOPAN CITY,CAYO,BELMOPAN JUNIOR COLLEGE,8/28/2000,Graduated,6/2/2002,...,3.0,10.5,3.00,CMPS314,ALGORITHMS,B+,3.0,10.5,3.5,2.94
8339,8340,7/9/1979,M,Mestizo,BELIZE CITY,BELIZE,UNIVERSITY OF BELIZE,8/13/2007,Graduated,6/14/2014,...,3.0,9.0,2.76,CMPS244,WEB APPLICATION DEV. 1,B,3.0,9.0,3.0,3.08
8367,8368,2/24/1981,F,Unknown,BELIZE CITY,BELIZE,UNIVERSITY OF BELIZE,8/13/2007,Graduated,6/15/2013,...,0.0,0.0,3.00,CMPS4111,DATABASE MANAGEMENT SYSTEMS II,WF,3.0,0.0,0.0,3.05
8393,8394,1/27/1979,M,Caucasian,BELMOPAN CITY,CAYO,FOREIGN,12/14/1999,Graduated,6/8/2003,...,4.0,14.0,3.74,MATH210,DIFFERENTIAL CALCULUS,B+,4.0,14.0,3.5,3.73
8422,8423,6/13/1978,F,Creole,BELIZE CITY,BELIZE,UNIVERSITY OF BELIZE,8/19/2013,Dropped,NaN,...,0.0,0.0,2.50,MATH1302,CALCULUS I,WF,3.0,0.0,0.0,2.01

In [161]:
#Number of students

bint_df_clean_unique["STUID"].value_counts()

1       1
5705    1
5911    1
5899    1
5891    1
       ..
2916    1
2895    1
2892    1
2888    1
8423    1
Name: STUID, Length: 436, dtype: int64

In [162]:
student_count = bint_df_clean_unique["STUID"].value_counts().sum()

In [163]:
student_count

436

In [164]:
#Number of students who graduated

students_graduated_df = bint_df_clean_unique[bint_df_clean_unique["PROGRAMSTATUS"] == "Graduated"]

In [165]:
students_graduated = students_graduated_df["STUID"].nunique()

In [166]:
students_graduated

232

In [167]:
#Gender breakdown

bint_df_clean_unique.groupby("GENDER")["GENDER"].count()

GENDER
F     97
M    339
Name: GENDER, dtype: int64

In [168]:
#Ethnicity breakdown

bint_df_clean_unique.groupby("ETHNICITY")["ETHNICITY"].count().sort_values(ascending = False)

ETHNICITY
Mestizo        175
Creole         118
Other           40
Unknown         28
Oriental        23
Garifuna        19
East Indian     15
Mayan           15
Caucasian        2
Ketchi           1
Name: ETHNICITY, dtype: int64

In [169]:
#Grade breakdown

bint_df_clean.groupby("COURSEGRADE")["COURSEGRADE"].count()

COURSEGRADE
A      909
A-    1304
AU      18
B     1397
B+    1450
C      812
C+     978
D      232
D+     243
F      444
NG      39
NR       5
P       26
RE      81
W      108
WF     151
WP      58
Name: COURSEGRADE, dtype: int64

In [170]:
#Average number of years to graduate from BINT

#This creates a copy of the DataFrame without affecting the original DataFrame.
bint_df_clean_unique_copy = bint_df_clean_unique.copy()

#Convert PROGRAMSTART and PROGRAMEND columns to datetime
bint_df_clean_unique_copy["PROGRAMSTART"] = pd.to_datetime(bint_df_clean_unique_copy["PROGRAMSTART"])
bint_df_clean_unique_copy["PROGRAMEND"] = pd.to_datetime(bint_df_clean_unique_copy["PROGRAMEND"])

#Calculate difference between PROGRAMEND and PROGRAMSTART columns
bint_df_clean_unique_copy["PROGRAMDURATION"] = (bint_df_clean_unique_copy["PROGRAMEND"] - bint_df_clean_unique_copy["PROGRAMSTART"]).dt.days / 365

# Calculate average number of years
average_duration = bint_df_clean_unique_copy["PROGRAMDURATION"].mean()

In [171]:
#Average in years

average_duration

2.9513288842055965

In [172]:
#Where the students are living

bint_df_clean_unique.groupby("CITY")["CITY"].count()

CITY
-                           66
BELIZE                       8
BELIZE CITY                 89
BELIZE DISTRICT              1
BELMOPAN                    24
BELMOPAN CITY               86
BENQUE VIEJO DEL CARMEN     11
BENQUE VIEJO ROAD            1
BULLET TREE FALLS            2
BURRELL BOOM VILLAGE         2
BUTTONWOOD BAY               1
Belize                       2
CAMALOTE VILLAGE             1
CAYE CAULKER                 1
CAYO                        14
CAYO DISTRICT                2
COROZAL                      2
COROZAL DISTRICT             2
COROZAL TOWN                11
DANGRIGA TOWN               16
HATTIEVILLE VILLAGE          1
INDEPENDENCE VILLAGE         1
JANE USHER AREA              1
LADYVILLE VILLAGE            3
LORDS BANK                   1
NIGERIA                      2
ORANGE WALK                 14
ORANGE WALK DISTRICT         3
ORANGE WALK TOWN            13
Orange Walk Town             1
PUNTA GORDA                  2
PUNTA GORDA TOWN             1
ROARING CREEK VILLAGE        2
SAN IGNACIO                 18
SAN IGNACIO TOWN             4
SAN JOSE SUCCOTZ VILLAGE     1
SAN LAZARO VILLAGE           1
SAN NARCISO VILLAGE          2
SAN PABLO VILLAGE            1
SAN PEDRO                    1
SAN ROMAN VILLAGE            1
SANDHILL VILLAGE             1
SANTA ELENA                  2
STANN CREEK                  8
STANN CREEK DISTRICT         1
TOLEDO                       1
TRIAL FARM                   1
WESTERN HIGHWAY              1
Name: CITY, dtype: int64

In [173]:
#Which school district are they coming from?

bint_df_clean_unique.groupby("FEEDER")["FEEDER"].count()

FEEDER
 STANN CREEK ECUMENICAL HIGH SC         6
 WESLEY JUNIOR COLLEGE                 10
*UNKNOWN                                8
ADULT & CONTINUING EDUCATION            1
BELIZE ADVENTIST COLLEGE                3
BELIZE ADVENTIST JUNIOR COLLEGE         4
BELIZE CHRISTIAN ACADEMY                3
BELIZE COLLEGE OF AGRICULTURE           1
BELIZE TECHNICAL COLLEGE                3
BELMOPAN COMPREHENSIVE SCHOOL           9
BELMOPAN JUNIOR COLLEGE                 4
COROZAL JUNIOR COLLEGE                 12
EDEN SDA HIGH                           1
EDWARD P. YORKE                         2
ESCUELA MEXICO JR COLLEGE              14
FOREIGN                                 8
INDEPENDENCE JUNIOR COLLEGE             7
LADYVILLE TECHNICAL HIGH                1
MOPAN TECHNICAL HIGH SCHOOL             1
MUFFLES JUNIOR COLLEGE                 10
OUR LADY OF GUADALUPE HIGH SCH          1
SACRED HEART COLLEGE                    5
SACRED HEART JUNIOR COLLEGE            26
ST. CATHERINE ACADEMY                   3
ST. JOHN'S COLLEGE                      2
ST. JOHN'S COLLEGE JUNIOR COLLEGE      65
STANN CREEK ECUMENICAL JR. COLLEGE      5
TOLEDO COMMUNITY COLLEGE                1
UNIVERSITY COLLEGE OF BELIZE            3
UNIVERSITY OF BELIZE                  209
UNIVERSITY OF THE WEST INDIES           1
Name: FEEDER, dtype: int64

In [174]:
#How many female graduates?

females_graduated_df = bint_df_clean_unique[bint_df_clean_unique['GENDER'] == 'F']

In [175]:
females_graduated_data = females_graduated_df[females_graduated_df["PROGRAMSTATUS"] == "Graduated"]

In [176]:
females_graduated = females_graduated_data["STUID"].nunique()

In [177]:
females_graduated

58